// GUIAPZ: agrega y actualiza las fichas en este archivo.
// Usa una o varias categorías disponibles en app.js. Las fotos son rutas relativas a index.html.
// Publica fotos propias o con permiso. Confirma los datos antes de cambiar locationConfirmed, contactsConfirmed u hoursConfirmed a true.
window.GUIAPZ_PLACES = [
  {
    id: 7,
    isDemo: false,
    name: 'Walmart Pérez Zeledón',
    categories: ['Supermercados', 'Tiendas'],
    sections: ['Comercio'],
    type: 'market',
    emoji: '🛒',
    district: 'San Isidro de El General',
    districtConfirmed: true,
    area: 'Barrio Lourdes · Carretera Interamericana',
    description: 'Hipermercado con abarrotes, artículos para el hogar, tecnología, línea blanca, ropa, farmacia, servicios financieros y área de alimentos.',
    photos: [{src: 'images/walmart.jpg', alt: 'Vista aérea de Walmart Pérez Zeledón en Barrio Lourdes'}],
    locationConfirmed: true,
    latitude: 9.35032,
    longitude: -83.67443,
    address: 'Carretera Interamericana, 800 metros norte del Mall Plaza General, frente a Auto Mundial, Barrio Lourdes, San Isidro de El General, Pérez Zeledón, San José, Costa Rica.',
    hours: 'Lunes a domingo, 7:00 a. m. a 10:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      phone: '800-800-0722',
      facebook: 'https://www.facebook.com/WalmartCostaRica',
      website: 'https://www.walmart.co.cr/'
    },
    contactsConfirmed: true,
    mapsUrl: 'https://maps.app.goo.gl/5FYJrH9TmBwiP37m8'
  },
  {
    id: 8,
    isDemo: false,
    name: 'Pequeño Mundo Pérez Zeledón',
    categories: ['Tiendas'],
    sections: ['Comercio'],
    type: 'shop',
    emoji: '🛍️',
    district: 'Daniel Flores',
    districtConfirmed: true,
    area: 'Río Seco · Villa Ligia',
    description: 'Tienda por departamentos con artículos para el hogar, decoración, cocina, ferretería, tecnología, juguetes, productos de temporada y comestibles.',
    photos: [{src: 'images/pequenomundo.png', alt: 'Sucursal de Pequeño Mundo en Pérez Zeledón'}],
    locationConfirmed: true,
    latitude: 9.3604125,
    longitude: -83.6871406,
    address: 'Río Seco, Villa Ligia, 190 metros al oeste del templo católico Las Brisas, distrito Daniel Flores, Pérez Zeledón, San José, Costa Rica.',
    mapsUrl: 'https://maps.google.com/?cid=1964850723313404029',
    hours: 'Lunes a domingo, 9:00 a. m. a 8:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      phone: '+506 2208 2817',
      facebook: 'https://www.facebook.com/pequenomundocr',
      website: 'https://tienda.pequenomundo.com/'
    },
    contactsConfirmed: true
  },
  {
    id: 9,
    isDemo: false,
    name: 'Centro Comercial C-Town',
    categories: ['Centros comerciales'],
    sections: ['Comercio', 'Servicios'],
    type: 'shop',
    emoji: '🏬',
    district: 'San Isidro de El General',
    districtConfirmed: true,
    area: 'Centro · cercanías',
    description: 'Centro comercial con tiendas, opciones de comida, servicios y distintos establecimientos para hacer compras y resolver diligencias en Pérez Zeledón.',
    photos: [],
    locationConfirmed: false,
    latitude: null,
    longitude: null,
    address: 'San Isidro de El General, Pérez Zeledón, San José, Costa Rica.',
    mapsUrl: 'https://maps.google.com/?cid=13416489370376655609',
    hours: 'Lunes a sábado, 8:00 a. m. a 9:00 p. m.; domingo, 9:00 a. m. a 8:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      phone: '+506 4000 3542',
      facebook: 'https://www.facebook.com/Ctowncr/?locale=es_LA'
    },
    contactsConfirmed: true
  },
  {
    id: 10,
    isDemo: false,
    name: 'Supermercado CoopeAgri Central',
    categories: ['Supermercados'],
    sections: ['Comercio'],
    type: 'market',
    emoji: '🛒',
    district: 'San Isidro de El General',
    districtConfirmed: true,
    area: 'Centro · frente al Mercado Municipal',
    description: 'Supermercado cooperativo con abarrotes, carnicería, verduras, panadería, artículos para el hogar y productos nacionales.',
    photos: [{src: 'images/coopeagri.png', alt: 'Supermercado CoopeAgri Central en San Isidro de El General'}],
    locationConfirmed: true,
    latitude: 9.37194,
    longitude: -83.70483,
    address: '200 metros al suroeste del Parque de San Isidro, frente al Mercado Municipal, San Isidro de El General, Pérez Zeledón, San José, Costa Rica.',
    mapsUrl: 'https://maps.google.com/?cid=10699949699389914833',
    hours: 'Lunes a sábado, 7:00 a. m. a 9:00 p. m.; domingo, 8:00 a. m. a 5:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      phone: '+506 2785 0227',
      facebook: 'https://www.facebook.com/CoopeAgriPZ',
      website: 'https://www.coopeagri.co.cr/negocios/supermercados/'
    },
    contactsConfirmed: true
  },
  {
    id: 11,
    isDemo: false,
    name: 'Gym City Fitness',
    categories: ['Gimnasios'],
    sections: ['Salud y bienestar'],
    type: 'gym',
    emoji: '🏋️',
    district: 'San Isidro de El General',
    districtConfirmed: true,
    area: 'Barrio San Luis · cerca de CoopeAgri',
    description: 'Gimnasio para acondicionamiento físico, musculación y rutinas de entrenamiento personalizadas.',
    photos: [],
    locationConfirmed: true,
    latitude: 9.38616,
    longitude: -83.70653,
    address: 'Barrio San Luis, 50 metros al norte del Supermercado CoopeAgri, San Isidro de El General, Pérez Zeledón, San José, Costa Rica.',
    mapsUrl: 'https://maps.google.com/?cid=7073575774324724879',
    hours: 'Lunes a viernes, 4:00 a. m. a medianoche; sábado, 7:00 a. m. a 5:00 p. m.; domingo, 9:00 a. m. a 1:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      whatsapp: '+506 8963 0701',
      phone: '+506 8963 0701',
      facebook: 'https://www.facebook.com/gymcityfitnesspz/'
    },
    contactsConfirmed: true
  },
  {
    id: 12,
    isDemo: false,
    name: 'Vitafuerte Fitness Center',
    categories: ['Gimnasios'],
    sections: ['Salud y bienestar'],
    type: 'gym',
    emoji: '💪',
    district: 'San Isidro de El General',
    districtConfirmed: true,
    area: 'Barrio Sagrada Familia · cerca de AgriStore',
    description: 'Centro de acondicionamiento físico con equipo de fuerza y cardio, clases dirigidas y rutinas personalizadas para distintos objetivos.',
    photos: [{src: 'images/vitafuerte.jpg', alt: 'Instalaciones de Vitafuerte Fitness Center en Pérez Zeledón'}],
    locationConfirmed: true,
    latitude: 9.36357,
    longitude: -83.69359,
    address: 'Barrio Sagrada Familia, 75 metros al este del supermercado AgriStore, Pérez Zeledón, San José, Costa Rica.',
    mapsUrl: 'https://maps.google.com/?cid=10528431461305947101',
    hours: 'Lunes a viernes, 4:00 a. m. a 10:00 p. m.; sábado, 7:00 a. m. a 5:00 p. m.; domingo, 8:00 a. m. a 1:00 p. m.',
    hoursConfirmed: true,
    contacts: {
      whatsapp: '+506 8528 5666',
      phone: '+506 8528 5666',
      facebook: 'https://www.facebook.com/vitafuertefitnesscenter/',
      website: 'https://www.vitafuerte.com/gimnasios/vitafuerte-fitness-center-perez-zeledon/'
    },
    contactsConfirmed: true
  }
];
